### ISSUE TITLE
code snippet (ch.10): stray line on pg. 320 + missing `>= 0`

### ISSUE THREAD

**Issue by profnandaa** [zodiacon/windowskernelprogrammingbook2e#20]
There's a stray line as highlighted and also `FindProcess` is missing `>= 0` on the condition check.

![image](https://github.com/zodiacon/windowskernelprogrammingbook2e/assets/261265/230d6c02-5ba4-4cc2-80ba-448c7cad2ea4)

**Comment by zodiacon** [comment]
Checking.

**Comment by zodiacon** [comment]
My bad. fixing.

**Comment by profnandaa** [comment]
fixed in the latest ed.
