### ISSUE TITLE
Question about kernelmode sockets (wsk.h)

### ISSUE THREAD

**Issue by AlSch092** [zodiacon/windowskernelprogrammingbook2e#33]
Hi Pavel, good day,

I'm a bit more than halfway through your book (which has been great so far), and I noticed there were no sections regarding kernelmode sockets, in particular how a driver can act as a client to a remote server. Would you happen to have any working examples of this, such that a driver can act as a TCP client and connect to a remote server & send/recv data? I'm aware that wsk.h and netioapi.h are used for this, but the examples I'm finding online either don't compile or simply don't work. I think it could make a good addition to your book in any future versions that you release, as there are probably many others who would be interested in this.

Cheers,
AlSch092

**Comment by zodiacon** [comment]
Thanks for the suggestion, it's a great idea for a future edition!
I know about the official sample in the WDK and also this one: https://github.com/wbenny/KSOCKET
