### ISSUE TITLE
minor errata: DbgView pg. 32

### ISSUE THREAD

**Issue by profnandaa** [zodiacon/windowskernelprogrammingbook2e#5]
Page 32 of 2nd Ed.

![image](https://user-images.githubusercontent.com/261265/233948132-65a8ce0c-d49f-4f61-a827-7fce9907fb35.png)

This should be "Capture menu" instead of "Options menu".

![image](https://user-images.githubusercontent.com/261265/233948581-7f96ad0b-2950-4a14-857e-c7cd1ca65d40.png)

**Comment by zodiacon** [comment]
Good catch. Will fix.

**Comment by profnandaa** [comment]
fixed
